
name: Docker Container Scan

on:
  push:
    branches:
      - '**'

jobs:
  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Ajoutez les étapes pour construire et analyser votre container Docker
